from django.core.management.base import BaseCommand
from core.models import ClinicalCase


PROFILES = {
    ClinicalCase.Category.BACTERIA: [
        dict(title='Lesão dolorosa na pele', pathogen='Staphylococcus aureus', diagnosis='Abscesso cutâneo por Staphylococcus aureus', complaint='Doutor, apareceu um caroço muito dolorido e quente na minha pele.', history='Lesão localizada, progressiva, com dor e calor; pode haver pequena drenagem purulenta. Sem trauma importante.', exam='Nódulo/flutuação localizada, hiperemia e dor; avaliar extensão, celulite e sinais sistêmicos.', tests='Em caso simples, diagnóstico é clínico; cultura de material profundo quando indicada, especialmente recorrência, falha ou gravidade.', management='Avaliar necessidade de drenagem, extensão e sinais sistêmicos; antibiótico somente quando indicado pelo quadro e protocolo local; orientar retorno.', red_flags='Toxicidade sistêmica, progressão rápida, imunossupressão, acometimento extenso ou localização de maior risco.', concept='S. aureus favorece abscessos; amostra profunda tem valor maior que swab superficial.', difficulty='BASIC'),
        dict(title='Ferida com crostas em criança', pathogen='Staphylococcus aureus', diagnosis='Impetigo bacteriano com participação provável de S. aureus', complaint='Meu filho está com umas feridinhas que formam crostas e estão aumentando.', history='Lesões superficiais contagiosas, prurido leve, sem sintomas sistêmicos importantes.', exam='Lesões superficiais crostosas; procurar extensão, bolhas, celulite e sinais sistêmicos.', tests='Geralmente clínico; cultura em formas extensas, recorrentes, surtos ou falha terapêutica.', management='Higiene, reduzir transmissão e escolher terapia tópica ou sistêmica conforme extensão e protocolo; reavaliar falha.', red_flags='Extensão rápida, febre, celulite, imunossupressão.', concept='Colonização e infecção não são equivalentes; extensão e profundidade orientam manejo.', difficulty='BASIC'),
        dict(title='Tosse e febre há poucos dias', pathogen='Streptococcus pneumoniae', diagnosis='Pneumonia adquirida na comunidade com suspeita de pneumococo', complaint='Estou com febre, tosse e dor no peito quando respiro fundo.', history='Início agudo, tosse produtiva, mal-estar e dor pleurítica; investigar idade, comorbidades e vacinação.', exam='Avaliar frequência respiratória, saturação, estado geral e achados focais pulmonares.', tests='Diagnóstico sindrômico; exames e imagem dependem de gravidade e dúvida diagnóstica.', management='Estratificar gravidade e local de cuidado; terapia antimicrobiana empírica conforme protocolos de PAC e perfil do paciente; orientar sinais de alarme.', red_flags='Hipoxemia, desconforto respiratório, hipotensão, confusão, incapacidade de hidratação.', concept='O sítio e a síndrome modificam a interpretação microbiológica e a escolha terapêutica.', difficulty='INTERMEDIATE'),
        dict(title='Ardência para urinar', pathogen='Escherichia coli', diagnosis='Cistite aguda não complicada provável por E. coli uropatogênica', complaint='Estou com muita ardência para urinar e vontade de ir ao banheiro toda hora.', history='Disúria, polaciúria e urgência; sem corrimento genital. Perguntar febre, dor lombar, gestação e recorrência.', exam='Geralmente estável; avaliar dor suprapúbica e sinais de pielonefrite.', tests='Urina tipo 1 e/ou cultura conforme perfil, recorrência, gestação, complicação ou falha.', management='Diferenciar cistite de pielonefrite e situações especiais; tratamento conforme protocolo local e padrões de resistência; orientar retorno.', red_flags='Febre alta, dor lombar, vômitos, gestação, sepse.', concept='E. coli pode ser comensal intestinal e, em clones uropatogênicos, causar ITU.', difficulty='BASIC'),
        dict(title='Febre e dor lombar com sintomas urinários', pathogen='Klebsiella pneumoniae', diagnosis='Infecção urinária febril/complicada com possível Klebsiella pneumoniae', complaint='Começou com ardência para urinar e agora estou com febre e dor nas costas.', history='Sintomas urinários seguidos de febre e dor lombar; investigar diabetes, litíase, instrumentação e antibiótico recente.', exam='Avaliar estado geral, hidratação, dor à punho-percussão lombar e sinais de sepse.', tests='Urina, urocultura e avaliação laboratorial conforme gravidade; imagem se suspeita de obstrução ou complicação.', management='Tratar como ITU febril/complicada, colher cultura quando indicada e definir necessidade de encaminhamento; ajustar terapia ao antibiograma.', red_flags='Sepse, obstrução urinária, gestação, vômitos persistentes, instabilidade.', concept='Klebsiella pode combinar virulência e resistência, mas esses eixos não são sinônimos.', difficulty='ADVANCED'),
        dict(title='Ferida crônica com secreção', pathogen='Pseudomonas aeruginosa', diagnosis='Infecção de ferida com risco de Pseudomonas aeruginosa em hospedeiro predisposto', complaint='Tenho uma ferida que não cicatriza e agora começou a soltar secreção e cheirar diferente.', history='Ferida crônica em paciente com fatores predisponentes; perguntar antibióticos prévios, internações e comorbidades.', exam='Avaliar profundidade, necrose, perfusão, celulite, dor desproporcional e sinais sistêmicos.', tests='Amostra profunda quando indicada; evitar interpretar colonização superficial como infecção invasiva.', management='Distinguir colonização de infecção, cuidar da ferida, avaliar necessidade de cultura e referência; terapia dirigida conforme microbiologia e protocolo.', red_flags='Necrose, sepse, isquemia, dor desproporcional, rápida progressão.', concept='Pseudomonas forma biofilme e pode colonizar superfícies; contexto clínico define relevância.', difficulty='ADVANCED'),
        dict(title='Dor abdominal após processo infeccioso', pathogen='Bacteroides fragilis', diagnosis='Infecção intra-abdominal com participação provável de Bacteroides fragilis', complaint='Minha barriga está doendo cada vez mais e comecei a ter febre.', history='Dor abdominal persistente após quadro compatível com ruptura de barreira intestinal; sintomas sistêmicos podem surgir.', exam='Dor localizada ou difusa, defesa; avaliar peritonismo e instabilidade.', tests='Imagem e avaliação hospitalar conforme quadro; se drenado, aspirado/tecido profundo é melhor que swab superficial para anaeróbios.', management='Reconhecer necessidade de avaliação urgente, controle de foco e cobertura adequada para flora intra-abdominal conforme protocolo.', red_flags='Peritonite, sepse, instabilidade, abdome agudo.', concept='Anaeróbios do cólon tornam-se patogênicos após quebra de barreira; amostra deve preservar anaerobiose.', difficulty='ADVANCED'),
        dict(title='Tosse persistente e emagrecimento', pathogen='Mycobacterium tuberculosis', diagnosis='Tuberculose pulmonar', complaint='Estou tossindo há semanas e perdi peso sem querer.', history='Tosse prolongada, perda ponderal, sudorese noturna e possível febre vespertina; investigar contatos e vulnerabilidades.', exam='Avaliar estado geral, sinais respiratórios e extrapulmonares; exame pode ser pouco específico.', tests='Teste rápido molecular, baciloscopia e cultura conforme algoritmo nacional e disponibilidade; testar HIV conforme rotina e consentimento.', management='Aplicar fluxo do SUS para investigação, notificação, tratamento padronizado e avaliação de contatos; reconhecer necessidade de referência conforme gravidade.', red_flags='Hemoptise importante, insuficiência respiratória, deterioração clínica importante.', concept='Parede rica em ácidos micólicos e crescimento lento exigem métodos diagnósticos próprios.', difficulty='INTERMEDIATE'),
        dict(title='Tosse seca em jovem', pathogen='Mycoplasma pneumoniae', diagnosis='Infecção respiratória por Mycoplasma pneumoniae', complaint='Estou com uma tosse seca que não passa e um pouco de febre.', history='Quadro respiratório subagudo, frequentemente em jovem, com tosse persistente e sintomas sistêmicos moderados.', exam='Ausculta pode ser pouco exuberante em relação à queixa; avaliar gravidade respiratória.', tests='Diagnóstico majoritariamente clínico/sindrômico; testes moleculares podem ser usados em cenários selecionados.', management='Avaliar gravidade e necessidade de antimicrobiano apropriado; evitar beta-lactâmico como terapia dirigida para Mycoplasma por ausência de parede.', red_flags='Hipoxemia, desconforto respiratório, deterioração sistêmica.', concept='Mycoplasma não possui parede celular; fármacos que dependem desse alvo não atuam.', difficulty='INTERMEDIATE'),
        dict(title='Disúria após nova parceria', pathogen='Chlamydia trachomatis', diagnosis='Uretrite/cervicite por Chlamydia trachomatis', complaint='Estou com ardência para urinar e um desconforto que começou há alguns dias.', history='Sintomas geniturinários leves; perguntar corrimento, dor pélvica/testicular, exposição sexual recente e possibilidade de gestação de forma respeitosa.', exam='Exame dirigido conforme sintomas, consentimento e contexto; procurar complicações.', tests='NAAT em amostra validada, como urina de primeiro jato ou swab apropriado.', management='Tratar conforme protocolo vigente, abordar parcerias, testagem para outras IST quando indicada, prevenção e seguimento.', red_flags='Dor pélvica intensa, febre, suspeita de DIP, dor testicular aguda, gestação com complicações.', concept='C. trachomatis é intracelular obrigatória e NAAT é método preferencial.', difficulty='INTERMEDIATE'),
    ],
    ClinicalCase.Category.FUNGI: [
        dict(title='Coceira entre os dedos dos pés', pathogen='Trichophyton spp.', diagnosis='Tinea pedis por dermatófito', complaint='Meus pés coçam muito e a pele entre os dedos está descascando.', history='Prurido, descamação interdigital, piora com umidade; perguntar uso de calçado fechado e recorrência.', exam='Descamação, fissuras e borda ativa; avaliar infecção bacteriana secundária.', tests='KOH de escamas da borda ativa quando necessário; cultura em casos atípicos/refratários.', management='Medidas para reduzir umidade e antifúngico tópico conforme extensão; reavaliar formas extensas ou refratárias.', red_flags='Celulite secundária, imunossupressão relevante, extensa maceração.', concept='Dermatófitos utilizam queratina; colher da borda ativa aumenta rendimento.', difficulty='BASIC'),
        dict(title='Lesão circular que coça', pathogen='Microsporum spp.', diagnosis='Tinea corporis por dermatófito', complaint='Apareceu uma mancha redonda que coça e está aumentando pelas bordas.', history='Lesão anular pruriginosa; perguntar contato com animais, pessoas afetadas e uso prévio de corticoide.', exam='Placa anular com borda ativa descamativa e clareamento central variável.', tests='KOH se dúvida; cultura em casos selecionados.', management='Antifúngico tópico ou sistêmico conforme extensão/local; evitar corticoide isolado.', red_flags='Extensão importante, imunossupressão, acometimento profundo.', concept='A borda ativa concentra estruturas fúngicas e é o melhor local para coleta.', difficulty='BASIC'),
        dict(title='Unha espessada e quebradiça', pathogen='Epidermophyton/Trichophyton spp.', diagnosis='Onicomicose dermatofítica', complaint='Minha unha está grossa, amarelada e quebrando há meses.', history='Alteração crônica ungueal; perguntar trauma, psoríase, diabetes e tratamentos anteriores.', exam='Espessamento, debris subungueal e distrofia; avaliar número de unhas e matriz.', tests='Confirmar micose antes de tratamento sistêmico com KOH/cultura ou método validado.', management='Escolher terapia conforme extensão, matriz, comorbidades e confirmação; orientar duração prolongada e cuidados locais.', red_flags='Infecção bacteriana associada, pé diabético, imunossupressão importante.', concept='Nem toda unha distrófica é micose; confirmação etiológica evita tratamento desnecessário.', difficulty='INTERMEDIATE'),
        dict(title='Placas brancas na boca', pathogen='Candida spp.', diagnosis='Candidíase oral', complaint='Minha boca está ardendo e apareceram umas placas brancas na língua e na bochecha.', history='Placas removíveis e ardor; perguntar antibiótico recente, prótese, corticoide inalatório, diabetes e imunossupressão.', exam='Placas brancas removíveis com base eritematosa; avaliar extensão e odinofagia.', tests='Geralmente clínico; investigar fatores predisponentes e doença esofágica se odinofagia.', management='Corrigir predisponentes quando possível e tratar conforme extensão; investigar imunossupressão se quadro recorrente/atípico.', red_flags='Odinofagia/disfagia importante, imunossupressão avançada, desidratação.', concept='Candida pode colonizar mucosas; doença depende de sítio e fatores do hospedeiro.', difficulty='BASIC'),
        dict(title='Prurido e corrimento vaginal', pathogen='Candida spp.', diagnosis='Candidíase vulvovaginal', complaint='Estou com muita coceira e um corrimento diferente.', history='Prurido vulvar, ardor e corrimento; perguntar recorrência, antibiótico, diabetes, gestação e sintomas sugestivos de outras causas.', exam='Eritema e corrimento compatível, quando exame for indicado e consentido.', tests='Diagnóstico clínico e microscópico conforme apresentação; cultura em recorrência/complicação.', management='Tratar conforme forma não complicada ou complicada e considerar situações especiais, incluindo gestação.', red_flags='Dor pélvica, febre, lesões ulceradas, suspeita de outra IST.', concept='Isolamento de Candida sem síndrome clínica pode representar colonização.', difficulty='INTERMEDIATE'),
        dict(title='Nódulos no braço após contato com gato', pathogen='Sporothrix spp.', diagnosis='Esporotricose linfocutânea', complaint='Começou uma feridinha no braço e depois apareceram outros caroços subindo pelo braço.', history='Lesão após arranhadura/contato com gato ou material vegetal; nódulos em cadeia linfática.', exam='Nódulos/úlceras ao longo de trajeto linfático; avaliar disseminação e sinais sistêmicos.', tests='Cultura de material profundo/biópsia conforme forma; exame direto pode ser negativo.', management='Confirmar forma clínica, orientar cuidado com animal e tratamento antifúngico conforme protocolo; notificação/vigilância conforme local.', red_flags='Disseminação, imunossupressão, acometimento ocular/osteoarticular, gestação.', concept='Inoculação cutânea e padrão linfático são pistas centrais; exame direto negativo não exclui.', difficulty='INTERMEDIATE'),
        dict(title='Tosse crônica e lesões na boca', pathogen='Paracoccidioides spp.', diagnosis='Paracoccidioidomicose crônica', complaint='Estou tossindo há meses e apareceram feridas doloridas na boca.', history='Adulto com exposição rural/solo, sintomas respiratórios crônicos, perda de peso e lesões mucosas.', exam='Lesões mucosas e sinais respiratórios; avaliar linfonodos e outros órgãos.', tests='Exame direto/histologia, cultura e sorologia conforme cenário; diferenciar de TB e neoplasia.', management='Confirmar etiologia, avaliar extensão e gravidade, iniciar tratamento prolongado conforme protocolo e acompanhar resposta.', red_flags='Insuficiência respiratória, comprometimento sistêmico importante, perda ponderal acentuada.', concept='Micose sistêmica por inalação; integração entre pulmão, mucosa e exposição é decisiva.', difficulty='ADVANCED'),
        dict(title='Febre prolongada em pessoa imunossuprimida', pathogen='Histoplasma capsulatum', diagnosis='Histoplasmose disseminada em imunossupressão', complaint='Estou com febre há semanas, muito cansado e emagrecendo.', history='Imunossupressão relevante, febre, perda ponderal; perguntar sintomas respiratórios, gastrointestinais e exposição ambiental.', exam='Pode haver hepatoesplenomegalia, adenomegalias e alterações mucocutâneas; avaliar gravidade.', tests='Antígeno, cultura, histologia e métodos moleculares conforme disponibilidade e sítio.', management='Reconhecer infecção oportunista potencialmente grave, investigar HIV/imunossupressão e encaminhar para manejo especializado quando necessário.', red_flags='Instabilidade, insuficiência respiratória, citopenias importantes, disfunção orgânica.', concept='Imunidade celular determina risco de disseminação em micoses sistêmicas.', difficulty='ADVANCED'),
        dict(title='Cefaleia persistente em imunossuprimido', pathogen='Cryptococcus spp.', diagnosis='Criptococose com suspeita de acometimento do SNC', complaint='Estou com uma dor de cabeça que não melhora e ando muito indisposto.', history='Imunossupressão, cefaleia subaguda, náuseas ou alterações cognitivas leves.', exam='Avaliar sinais neurológicos, estado mental e sinais de hipertensão intracraniana.', tests='Antígeno criptocócico e avaliação de SNC conforme indicação; punção lombar exige avaliação clínica adequada.', management='Suspeitar de infecção oportunista grave e encaminhar para investigação e tratamento especializado sem atraso.', red_flags='Alteração de consciência, déficit focal, convulsão, sinais de hipertensão intracraniana.', concept='Criptococose em imunossupressão pode envolver SNC e requer investigação urgente.', difficulty='ADVANCED'),
        dict(title='Falta de ar progressiva em paciente com HIV', pathogen='Pneumocystis jirovecii', diagnosis='Pneumocistose em imunossupressão avançada', complaint='Estou ficando sem ar até para fazer coisas simples e tenho uma tosse seca.', history='HIV ou imunossupressão, dispneia progressiva, tosse seca, febre; início subagudo.', exam='Taquipneia e possível hipoxemia; ausculta pode ser discreta.', tests='Imagem e demonstração molecular/microscópica conforme protocolo; avaliar oxigenação.', management='Reconhecer gravidade, iniciar fluxo de cuidado para infecção oportunista e avaliar necessidade de hospitalização.', red_flags='Hipoxemia, desconforto respiratório, piora rápida.', concept='Oportunismo depende fortemente da imunidade celular e do grau de imunossupressão.', difficulty='ADVANCED'),
    ],
    ClinicalCase.Category.VIRUS: [
        dict(title='Febre alta e dor no corpo', pathogen='Dengue virus', diagnosis='Dengue', complaint='Estou com febre alta, muita dor no corpo e atrás dos olhos.', history='Febre aguda, cefaleia, mialgia; perguntar dia de doença, sangramentos, dor abdominal, vômitos e hidratação.', exam='Avaliar sinais de alarme, perfusão, pressão, hidratação e sangramentos.', tests='Hemograma e testes específicos conforme dia de sintomas e classificação de risco; interpretação depende do contexto.', management='Classificar risco conforme protocolo de dengue, hidratar adequadamente, evitar medicamentos contraindicados e programar reavaliação.', red_flags='Dor abdominal intensa, vômitos persistentes, sangramento importante, letargia, hipotensão, sinais de choque.', concept='Plaquetas isoladas não definem gravidade; dia de doença e sinais de alarme orientam manejo.', difficulty='INTERMEDIATE'),
        dict(title='Exantema e coceira com conjuntivite', pathogen='Zika virus', diagnosis='Infecção por Zika vírus', complaint='Apareceram manchas pelo corpo que coçam e meus olhos ficaram vermelhos.', history='Exantema pruriginoso, conjuntivite não purulenta, febre baixa; perguntar gestação ou possibilidade de gestação e exposição a mosquitos.', exam='Exantema, conjuntivite, artralgia; avaliar diferenciais e sinais de gravidade.', tests='Diagnóstico depende de janela temporal e contexto epidemiológico; métodos moleculares/sorológicos conforme protocolo.', management='Manejo sintomático, prevenção de transmissão vetorial e atenção especial a gestantes/risco gestacional conforme protocolos.', red_flags='Sintomas neurológicos, gestação com quadro suspeito, deterioração clínica.', concept='Arboviroses compartilham vetor e sintomas; contexto temporal/epidemiológico muda a probabilidade.', difficulty='INTERMEDIATE'),
        dict(title='Febre e dores articulares intensas', pathogen='Chikungunya virus', diagnosis='Chikungunya', complaint='Tive febre e minhas articulações começaram a doer muito, principalmente mãos e tornozelos.', history='Febre aguda com poliartralgia intensa; perguntar edema, duração e limitações funcionais.', exam='Dor/edema articular, exantema possível; avaliar sinais de gravidade e diferenciais.', tests='Confirmação conforme fase e epidemiologia; considerar diagnóstico diferencial com dengue e Zika.', management='Manejo sintomático conforme fase, excluir dengue antes de certas escolhas farmacológicas e acompanhar persistência articular.', red_flags='Comprometimento neurológico, cardíaco, desidratação ou extremos de idade com piora.', concept='Artralgia intensa e persistente é pista, mas arboviroses exigem diferenciação contextual.', difficulty='INTERMEDIATE'),
        dict(title='Febre, tosse e início súbito', pathogen='Influenza virus', diagnosis='Síndrome gripal por influenza', complaint='Comecei de repente com febre, tosse, dor no corpo e muito cansaço.', history='Início abrupto, febre, mialgia, tosse; perguntar fatores de risco, vacinação e tempo de sintomas.', exam='Avaliar frequência respiratória, saturação e sinais de complicação.', tests='Testes respiratórios conforme disponibilidade, janela temporal e impacto na conduta.', management='Suporte, isolamento respiratório conforme orientação vigente e considerar antiviral nos grupos/tempos indicados pelo protocolo.', red_flags='Dispneia, hipoxemia, piora após melhora inicial, alteração de consciência.', concept='O tempo desde o início dos sintomas influencia utilidade de teste e de antiviral.', difficulty='BASIC'),
        dict(title='Tosse, febre e contato domiciliar', pathogen='SARS-CoV-2', diagnosis='COVID-19', complaint='Estou com tosse, febre e perdi um pouco o olfato depois que alguém em casa ficou doente.', history='Síndrome respiratória aguda; perguntar exposição, vacinação, fatores de risco e início.', exam='Avaliar saturação e sinais de gravidade respiratória.', tests='Teste de antígeno ou molecular conforme tempo e indicação; interpretar junto à probabilidade clínica.', management='Suporte e medidas de prevenção conforme recomendações vigentes; avaliar elegibilidade a terapias específicas em grupos de risco.', red_flags='Hipoxemia, dispneia progressiva, dor torácica persistente, alteração de consciência.', concept='Detecção viral precisa ser interpretada pela janela temporal e contexto clínico.', difficulty='BASIC'),
        dict(title='Perda de peso e infecções recorrentes', pathogen='HIV-1/2', diagnosis='Infecção pelo HIV a esclarecer/confirmar em fluxo diagnóstico', complaint='Tenho emagrecido e tive algumas infecções que nunca costumava ter.', history='Sintomas inespecíficos; explorar exposições de forma não julgadora, história de IST, testes prévios e sinais de imunossupressão.', exam='Exame geral dirigido a infecções oportunistas e sinais sistêmicos.', tests='Seguir algoritmo diagnóstico do SUS com testes de triagem/confirmatórios; carga viral e CD4 após diagnóstico conforme fluxo.', management='Aconselhamento, testagem conforme protocolo, vinculação rápida ao cuidado e terapia antirretroviral quando confirmado.', red_flags='Infecção oportunista grave, sintomas neurológicos, hipoxemia, deterioração sistêmica.', concept='HIV estabelece reservatórios; carga viral e CD4 respondem a perguntas diferentes.', difficulty='ADVANCED'),
        dict(title='Cansaço e alteração de enzimas hepáticas', pathogen='Hepatitis B virus', diagnosis='Hepatite B a esclarecer por painel sorológico', complaint='Fiz exames e disseram que minhas enzimas do fígado estão alteradas; ando cansado.', history='Pode ser assintomática; perguntar exposições, vacinação, sintomas de hepatite e história familiar.', exam='Avaliar icterícia, hepatomegalia e sinais de doença hepática avançada.', tests='Interpretar conjuntamente HBsAg, anti-HBc total/IgM, anti-HBs e marcadores adicionais conforme cenário.', management='Definir fase da infecção com painel adequado e encaminhar/seguir PCDT para monitoramento e tratamento quando indicado.', red_flags='Encefalopatia, coagulopatia, icterícia intensa, ascite ou sinais de insuficiência hepática.', concept='Um único marcador de HBV raramente responde sozinho à pergunta clínica.', difficulty='ADVANCED'),
        dict(title='Anti-HCV positivo em rastreamento', pathogen='Hepatitis C virus', diagnosis='Exposição ao HCV com necessidade de confirmar infecção ativa', complaint='Meu exame de hepatite C veio positivo e estou preocupado.', history='Frequentemente assintomático; perguntar exposições, tratamentos prévios e sinais de doença hepática.', exam='Avaliar sinais de hepatopatia crônica.', tests='Anti-HCV indica exposição; RNA do HCV confirma infecção ativa.', management='Confirmar viremia, estadiar doença hepática e seguir PCDT para terapia antiviral e acompanhamento.', red_flags='Sinais de descompensação hepática.', concept='Anticorpo anti-HCV positivo não equivale necessariamente a infecção ativa.', difficulty='INTERMEDIATE'),
        dict(title='Lesão verrucosa genital', pathogen='Human papillomavirus (HPV)', diagnosis='Infecção anogenital por HPV com condiloma', complaint='Percebi uma verruguinha na região genital e fiquei preocupado.', history='Lesão verrucosa sem sintomas sistêmicos; abordar história sexual e vacinação com linguagem respeitosa e não julgadora.', exam='Inspeção clínica quando consentida; avaliar número, localização e lesões atípicas.', tests='Condilomas costumam ser diagnóstico clínico; rastreamento cervical segue protocolo próprio e não é equivalente ao diagnóstico de verruga.', management='Tratar lesões conforme opções disponíveis, orientar prevenção/vacinação e rastreamento conforme idade/sexo/protocolo.', red_flags='Lesão ulcerada, pigmentada, endurecida, sangramento persistente ou imunossupressão importante.', concept='HPV detectável não equivale a câncer; vacinação e rastreamento atuam em etapas diferentes.', difficulty='INTERMEDIATE'),
        dict(title='Febre, tosse e exantema em não vacinado', pathogen='Measles virus', diagnosis='Sarampo suspeito', complaint='Estou com febre, tosse, olhos vermelhos e agora apareceram manchas no corpo.', history='Febre, tosse/coriza/conjuntivite seguidas de exantema; perguntar vacinação e viagem/contato.', exam='Exantema e sinais respiratórios; avaliar gravidade e isolamento.', tests='Notificação e coleta conforme vigilância; confirmação laboratorial/epidemiológica conforme protocolo vigente.', management='Isolamento, notificação imediata, suporte e articulação com vigilância; avaliar contatos e vacinação conforme normas.', red_flags='Pneumonia, encefalite, desidratação, piora em imunossuprimido.', concept='Eliminação da transmissão endêmica não significa erradicação; casos importados continuam possíveis.', difficulty='ADVANCED'),
    ],
    ClinicalCase.Category.PARASITE: [
        dict(title='Dor abdominal após banho de rio', pathogen='Schistosoma mansoni', diagnosis='Esquistossomose mansônica intestinal/hepática inicial', complaint='Tenho tido dor na barriga e lembrei que costumo entrar em água de rio na zona rural.', history='Exposição a água doce em área de risco, sintomas intestinais variáveis; perguntar sangue nas fezes e história de exposição prolongada.', exam='Avaliar abdome, fígado/baço e sinais de hipertensão portal nas formas crônicas.', tests='Pesquisa de ovos em fezes e métodos complementares conforme carga e contexto.', management='Confirmar diagnóstico, tratar conforme protocolo e avaliar extensão/complicações; orientar prevenção de nova exposição.', red_flags='Hemorragia digestiva, ascite, esplenomegalia importante, sinais de hipertensão portal.', concept='A morbidade crônica decorre principalmente da reação granulomatosa aos ovos retidos.', difficulty='INTERMEDIATE'),
        dict(title='Barriga inchada e vermes nas fezes', pathogen='Ascaris lumbricoides', diagnosis='Ascaridíase intestinal', complaint='Estou com a barriga estufada e vi algo parecido com verme nas fezes.', history='Desconforto abdominal; perguntar saneamento, geofagia e sintomas de obstrução.', exam='Geralmente inespecífico; avaliar distensão e sinais obstrutivos.', tests='Ovos em exame parasitológico de fezes; verme adulto pode ser identificado quando eliminado.', management='Tratar conforme protocolo, orientar saneamento/higiene e investigar complicação se sintomas obstrutivos.', red_flags='Dor intensa, vômitos biliosos, distensão progressiva, icterícia.', concept='Ingestão de ovos inicia ciclo com migração larvária antes do intestino adulto.', difficulty='BASIC'),
        dict(title='Cansaço e anemia com hábito de andar descalço', pathogen='Ancylostoma/Necator spp.', diagnosis='Ancilostomíase com anemia ferropriva', complaint='Estou muito cansado e disseram que estou anêmico; vivo andando descalço na roça.', history='Fadiga, exposição ao solo, dieta e possível desconforto abdominal.', exam='Palidez; avaliar gravidade da anemia e estado nutricional.', tests='Ovos em fezes e hemograma; diferenciação de espécie pode exigir métodos adicionais.', management='Tratar helmintíase e anemia conforme protocolo; orientar calçados, saneamento e reavaliação hematológica.', red_flags='Anemia grave, dispneia, síncope, sangramento evidente.', concept='Larvas penetram pela pele e a perda crônica intestinal pode contribuir para anemia.', difficulty='BASIC'),
        dict(title='Dor abdominal recorrente antes de usar corticoide', pathogen='Strongyloides stercoralis', diagnosis='Estrongiloidíase crônica', complaint='Tenho episódios de dor na barriga e diarreia que vão e voltam há muito tempo.', history='Exposição a solo; sintomas intermitentes. Perguntar imunossupressão atual ou planejada.', exam='Pode ser normal; avaliar estado nutricional e sinais respiratórios em formas graves.', tests='Pesquisa seriada de larvas e métodos de concentração/serologia conforme cenário.', management='Tratar antes de imunossupressão quando indicado e reconhecer risco de hiperinfecção; orientar seguimento.', red_flags='Imunossupressão, dispneia, sepse, sintomas gastrointestinais intensos.', concept='Autoinfecção permite persistência por anos e explica risco de hiperinfecção na imunossupressão.', difficulty='ADVANCED'),
        dict(title='Febre após ingestão de alimento artesanal', pathogen='Trypanosoma cruzi', diagnosis='Doença de Chagas aguda por possível transmissão oral', complaint='Depois de uma viagem comecei com febre que não passa e estou muito indisposto.', history='Febre prolongada após possível exposição oral/vetorial; investigar edema, palpitações e outras pessoas expostas.', exam='Pode haver edema, hepatomegalia, taquicardia; avaliar sinais cardíacos.', tests='Na fase aguda, métodos diretos e moleculares têm maior utilidade devido à parasitemia.', management='Notificar/investigar conforme vigilância, confirmar rapidamente e encaminhar para tratamento específico e avaliação cardíaca.', red_flags='Miocardite, arritmia, insuficiência cardíaca, sinais neurológicos.', concept='Na fase aguda a parasitemia é maior, mudando a estratégia diagnóstica.', difficulty='ADVANCED'),
        dict(title='Palpitações em pessoa com histórico rural', pathogen='Trypanosoma cruzi', diagnosis='Doença de Chagas crônica com possível cardiopatia', complaint='Tenho palpitações e às vezes fico tonto; cresci numa casa de taipa no interior.', history='Exposição remota; sintomas cardíacos ou digestivos. Perguntar síncope, dispneia e disfagia/constipação importante.', exam='Avaliação cardiovascular e sinais de insuficiência; exame digestivo dirigido.', tests='Sorologia com princípios metodológicos distintos para confirmação crônica; ECG e avaliação cardíaca conforme sintomas.', management='Confirmar infecção, estadiar forma clínica e encaminhar/acompanhar conforme diretrizes; avaliar indicação de tratamento etiológico individualmente.', red_flags='Síncope, arritmia sustentada, insuficiência cardíaca, fenômenos tromboembólicos.', concept='Na fase crônica a baixa parasitemia torna a sorologia o eixo da confirmação.', difficulty='ADVANCED'),
        dict(title='Febre prolongada e barriga aumentada', pathogen='Leishmania infantum', diagnosis='Leishmaniose visceral', complaint='Estou com febre há semanas, emagreci e minha barriga parece estar aumentando.', history='Febre prolongada, perda ponderal, fraqueza; perguntar exposição territorial e contato com áreas de transmissão.', exam='Hepatoesplenomegalia, palidez e possível sangramento; avaliar gravidade.', tests='Testes rápidos/sorologia, parasitológico e molecular conforme contexto, população e disponibilidade.', management='Suspeitar precocemente, confirmar conforme algoritmo e encaminhar para tratamento específico; avaliar coinfecção por HIV e gravidade.', red_flags='Sangramento, infecção bacteriana associada, citopenias graves, instabilidade.', concept='Amastigotas parasitam células do sistema mononuclear fagocitário, relacionando-se às citopenias e visceromegalias.', difficulty='ADVANCED'),
        dict(title='Diarreia após água não tratada', pathogen='Giardia duodenalis', diagnosis='Giardíase', complaint='Estou com diarreia, gases e barriga estufada depois de uma viagem onde bebi água de fonte.', history='Diarreia prolongada, distensão e possível esteatorreia/perda de peso; exposição a água não tratada.', exam='Avaliar hidratação e estado nutricional.', tests='Fezes seriadas, pesquisa de antígeno ou molecular; uma única amostra negativa pode falhar.', management='Reidratar se necessário, tratar conforme protocolo e orientar higiene/água segura.', red_flags='Desidratação importante, perda ponderal acentuada, imunossupressão.', concept='Eliminação de cistos pode ser intermitente; um resultado negativo isolado não exclui.', difficulty='BASIC'),
        dict(title='Diarreia com sangue e cólicas', pathogen='Entamoeba histolytica', diagnosis='Amebíase intestinal invasiva', complaint='Estou com cólicas e diarreia com sangue há alguns dias.', history='Diarreia disentérica, dor abdominal; perguntar viagem, água/alimentos e febre.', exam='Avaliar hidratação, dor e sinais peritoneais.', tests='Antígeno ou método molecular aumenta especificidade; microscopia isolada pode confundir espécies semelhantes.', management='Diferenciar outras causas de disenteria, tratar doença invasiva conforme protocolo e reidratar; avaliar complicações.', red_flags='Peritonismo, desidratação grave, toxemia, dor intensa.', concept='Microscopia inespecífica não distingue com segurança E. histolytica de amebas semelhantes.', difficulty='INTERMEDIATE'),
        dict(title='Febre e dor no lado direito do abdome', pathogen='Entamoeba histolytica', diagnosis='Abscesso hepático amebiano', complaint='Estou com febre e uma dor forte do lado direito da barriga, perto das costelas.', history='Febre e dor em hipocôndrio direito; história de exposição ou disenteria pode estar ausente.', exam='Dor hepática/hepatomegalia; avaliar sinais sistêmicos.', tests='Imagem hepática e sorologia/contexto; métodos etiológicos conforme cenário.', management='Reconhecer doença extraintestinal, confirmar e tratar conforme protocolo; encaminhar se gravidade ou dúvida diagnóstica.', red_flags='Instabilidade, sinais de ruptura, comprometimento torácico/pericárdico, sepse diferencial.', concept='E. histolytica pode invadir mucosa e alcançar fígado pela circulação portal.', difficulty='ADVANCED'),
    ],
}

NAMES = [
    ('Ana', 'Feminino', 24), ('Carlos', 'Masculino', 31), ('Beatriz', 'Feminino', 19), ('João', 'Masculino', 42),
    ('Marina', 'Feminino', 36), ('Rafael', 'Masculino', 27), ('Luciana', 'Feminino', 48), ('Pedro', 'Masculino', 22),
    ('Cláudia', 'Feminino', 55), ('Mateus', 'Masculino', 18), ('Renata', 'Feminino', 29), ('Antônio', 'Masculino', 63),
    ('Júlia', 'Feminino', 21), ('Bruno', 'Masculino', 34), ('Patrícia', 'Feminino', 40), ('Diego', 'Masculino', 25),
    ('Sônia', 'Feminino', 58), ('Lucas', 'Masculino', 20), ('Camila', 'Feminino', 32), ('José', 'Masculino', 51),
]

CATEGORY_PREFIX = {
    ClinicalCase.Category.BACTERIA: 'B',
    ClinicalCase.Category.FUNGI: 'F',
    ClinicalCase.Category.VIRUS: 'V',
    ClinicalCase.Category.PARASITE: 'P',
}


class Command(BaseCommand):
    help = 'Cria/atualiza os 80 casos clínicos iniciais (20 por categoria).'

    def handle(self, *args, **options):
        total = 0
        for category, profiles in PROFILES.items():
            if len(profiles) != 10:
                raise RuntimeError(f'A categoria {category} precisa ter exatamente 10 perfis-base.')
            order = 0
            for profile_index, p in enumerate(profiles):
                for variant in range(2):
                    order += 1
                    name, sex, base_age = NAMES[(order - 1) % len(NAMES)]
                    age = max(16, base_age + (variant * 3) - (profile_index % 2))
                    code = f"{CATEGORY_PREFIX[category]}{order:02d}"
                    variation = (
                        'Este é o primeiro episódio e o paciente ainda não usou tratamento específico.'
                        if variant == 0 else
                        'O paciente tentou apenas medidas caseiras/sintomáticas e procura a UBS porque o quadro persiste.'
                    )
                    master = {
                        'book_basis': 'Mecanismos de Agressão, Patológicos e de Defesa — capítulos de Microbiologia/Parasitologia Clínica.',
                        'spontaneous_information': p['complaint'],
                        'history_if_asked': p['history'],
                        'variant_note': variation,
                        'physical_exam_if_requested': p['exam'],
                        'tests_if_requested': p['tests'],
                        'aps_context': 'Atendimento educacional simulado em Unidade Básica de Saúde do SUS. O aluno deve reconhecer limites da APS e necessidade de referência quando aplicável.',
                        'communication_rule': 'O paciente não conhece o diagnóstico nem o agente e usa linguagem leiga. Não oferece dados ocultos sem ser perguntado.',
                    }
                    defaults = {
                        'category': category,
                        'order': order,
                        'public_title': p['title'],
                        'patient_name': name,
                        'age': age,
                        'sex': sex,
                        'difficulty': p['difficulty'],
                        'complaint': p['complaint'],
                        'pathogen': p['pathogen'],
                        'diagnosis': p['diagnosis'],
                        'master_context': master,
                        'expected_management': p['management'],
                        'red_flags': p['red_flags'],
                        'concept_anchor': p['concept'],
                        'active': True,
                    }
                    ClinicalCase.objects.update_or_create(code=code, defaults=defaults)
                    total += 1
        self.stdout.write(self.style.SUCCESS(f'{total} casos criados/atualizados com sucesso.'))
