# Generated for MAPD Casos initial deployment.
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth', '0012_alter_user_first_name_max_length')]

    operations = [
        migrations.CreateModel(name='User', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('password', models.CharField(max_length=128, verbose_name='password')), ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')), ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')), ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')), ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')), ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')), ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')), ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')), ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')), ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')), ('rgm', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='RGM')), ('turma', models.CharField(blank=True, max_length=80)), ('role', models.CharField(choices=[('STUDENT', 'Aluno'), ('PROFESSOR', 'Professor')], default='STUDENT', max_length=12)), ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')), ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'))], options={'verbose_name': 'user', 'verbose_name_plural': 'users', 'abstract': False}, managers=[('objects', django.contrib.auth.models.UserManager())]),
        migrations.CreateModel(name='ClinicalCase', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('code', models.CharField(max_length=12, unique=True)), ('category', models.CharField(choices=[('BACTERIA', 'Bactérias'), ('FUNGI', 'Fungos'), ('VIRUS', 'Vírus'), ('PARASITE', 'Parasitas')], db_index=True, max_length=12)), ('order', models.PositiveSmallIntegerField(default=1)), ('public_title', models.CharField(max_length=160)), ('patient_name', models.CharField(max_length=100)), ('age', models.PositiveSmallIntegerField()), ('sex', models.CharField(max_length=30)), ('difficulty', models.CharField(choices=[('BASIC', 'Básico'), ('INTERMEDIATE', 'Intermediário'), ('ADVANCED', 'Avançado')], default='BASIC', max_length=16)), ('complaint', models.TextField()), ('pathogen', models.CharField(max_length=160)), ('diagnosis', models.CharField(max_length=220)), ('master_context', models.JSONField(default=dict)), ('expected_management', models.TextField()), ('red_flags', models.TextField(blank=True)), ('concept_anchor', models.TextField(blank=True)), ('active', models.BooleanField(default=True))], options={'ordering': ['category', 'order', 'code']}),
        migrations.CreateModel(name='Encounter', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('status', models.CharField(choices=[('OPEN', 'Em andamento'), ('COMPLETED', 'Concluído')], default='OPEN', max_length=12)), ('outcome', models.CharField(choices=[('NOT_ASSESSED', 'Não avaliado'), ('ADEQUATE', 'Conduta adequada'), ('PARTIAL', 'Conduta parcialmente adequada'), ('INADEQUATE', 'Conduta inadequada')], default='NOT_ASSESSED', max_length=16)), ('score', models.PositiveSmallIntegerField(blank=True, null=True)), ('final_feedback', models.JSONField(blank=True, default=dict)), ('started_at', models.DateTimeField(auto_now_add=True)), ('completed_at', models.DateTimeField(blank=True, null=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='core.clinicalcase')), ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='core.user'))], options={'ordering': ['-updated_at']}),
        migrations.CreateModel(name='Message', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('role', models.CharField(choices=[('STUDENT', 'Aluno'), ('PATIENT', 'Paciente'), ('PRECEPTOR', 'Preceptor'), ('TUTOR', 'Lembre o conceito'), ('SYSTEM', 'Sistema')], max_length=12)), ('content', models.TextField()), ('created_at', models.DateTimeField(auto_now_add=True)), ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.encounter'))], options={'ordering': ['created_at', 'id']}),
        migrations.AddConstraint(model_name='clinicalcase', constraint=models.UniqueConstraint(fields=('category', 'order'), name='unique_case_order_per_category')),
        migrations.AddConstraint(model_name='encounter', constraint=models.UniqueConstraint(fields=('student', 'case'), name='unique_student_case_encounter')),
    ]
