"""Fluxos decisórios sem IA para os 20 casos bacterianos do MAPD Casos.

Cada par B01/B02, B03/B04 ... B19/B20 usa o mesmo cenário-base já presente no
seed, com ordem das alternativas embaralhada de forma determinística por caso.
"""
from __future__ import annotations

import hashlib
from copy import deepcopy

from .models import ClinicalCase

QUALITY = {
    "BEST": ("Melhor resposta", 4),
    "SUBOPTIMAL": ("Correta, mas subótima", 3),
    "PLAUSIBLE": ("Plausível, mas incorreta", 1),
    "WRONG": ("Totalmente incorreta", 0),
}

FEEDBACK = {
    "BEST": "É a decisão mais segura, proporcional e alinhada ao raciocínio baseado em evidências para este momento.",
    "SUBOPTIMAL": "A conduta tem fundamento, mas deixa de considerar um elemento importante do contexto, da gravidade ou do stewardship.",
    "PLAUSIBLE": "A alternativa parece defensável à primeira vista, mas se apoia em uma associação ou prioridade clínica inadequada.",
    "WRONG": "A conduta não responde ao problema central e pode atrasar diagnóstico, tratamento ou encaminhamento adequado.",
}

GENERAL_SOURCES = [
    {
        "title": "Ministério da Saúde — Protocolos Clínicos e Diretrizes Terapêuticas (PCDT)",
        "url": "https://www.gov.br/saude/pt-br/assuntos/pcdt/pcdt",
    },
    {
        "title": "Ministério da Saúde — Atenção Primária à Saúde",
        "url": "https://www.gov.br/saude/pt-br/composicao/saps/atencao-primaria",
    },
]


def D(node_id, stage, context, prompt, best, suboptimal, plausible, wrong, pearl=""):
    """Define um ponto de decisão com as quatro categorias pedagógicas."""
    options = []
    for idx, (text, quality) in enumerate(
        ((best, "BEST"), (suboptimal, "SUBOPTIMAL"), (plausible, "PLAUSIBLE"), (wrong, "WRONG"))
    ):
        label, points = QUALITY[quality]
        options.append({
            "id": f"{node_id}-{idx + 1}",
            "text": text,
            "quality": quality,
            "quality_label": label,
            "points": points,
            "feedback": FEEDBACK[quality],
        })
    return {
        "id": node_id,
        "stage": stage,
        "context": context,
        "prompt": prompt,
        "options": options,
        "pearl": pearl,
    }


SCENARIOS = {
    1: {
        "title": "Abscesso cutâneo provável por Staphylococcus aureus",
        "focus": "Coleção purulenta, S. aureus, drenagem, indicação seletiva de antibiótico e segurança.",
        "sources": GENERAL_SOURCES,
        "nodes": [
            D("triage", "Acolhimento", "Nódulo muito doloroso, quente e progressivo.",
              "Qual é a primeira decisão na UBS?",
              "Avaliar sinais sistêmicos, extensão, localização de risco, imunossupressão e presença de coleção/flutuação.",
              "Examinar a lesão e medir temperatura, deixando comorbidades para o retorno.",
              "Pedir hemograma antes de examinar para confirmar infecção bacteriana.",
              "Prescrever corticoide tópico e observar por uma semana.",
              "Coleção purulenta e celulite difusa exigem raciocínios relacionados, mas não idênticos."),
            D("etiology", "Agente etiológico", "Há flutuação, hiperemia e pequena drenagem purulenta.",
              "Qual associação agente–síndrome é a mais provável?",
              "Staphylococcus aureus — associação clássica com abscessos e infecções purulentas.",
              "Streptococcus pyogenes — possível em pele, porém mais típico de celulite/erisipela não purulenta.",
              "Pseudomonas aeruginosa — porque toda secreção purulenta indica Pseudomonas.",
              "Mycoplasma pneumoniae — por ser bactéria comunitária."),
            D("procedure", "Controle de foco", "Paciente estável, sem sinais sistêmicos; a coleção é acessível.",
              "Qual conduta trata diretamente o principal problema?",
              "Avaliar e realizar/encaminhar para incisão e drenagem quando indicada, com analgesia, curativo e retorno.",
              "Iniciar antibiótico contra cocos Gram-positivos e só depois reavaliar a necessidade de drenagem.",
              "Coletar swab superficial e aguardar cultura antes de intervir.",
              "Usar apenas anti-inflamatório por sete dias.",
              "Quando há coleção drenável, antibiótico não substitui controle de foco."),
            D("antibiotic", "Antimicrobianos", "Após drenagem adequada, segue estável e sem celulite extensa.",
              "Como pensar o antibiótico?",
              "Indicar conforme extensão, sinais sistêmicos, fatores do hospedeiro e protocolo local; não automatizar antibiótico em todo abscesso simples drenado.",
              "Prescrever antibiótico estreito contra cocos Gram-positivos em todos os casos drenados.",
              "Usar ciprofloxacino porque penetra bem em tecidos.",
              "Usar dois antibióticos amplos para prevenir resistência."),
            D("culture", "Microbiologia", "O paciente pergunta se precisa cultura do pus.",
              "Qual orientação é melhor?",
              "Em caso simples pode não ser necessária; considerar material profundo em recorrência, falha, gravidade ou risco de resistência.",
              "Fazer cultura em todo abscesso, mas dispensá-la se a drenagem for completa.",
              "Colher sempre swab da pele ao redor antes de drenar.",
              "Nunca cultivar porque S. aureus é sempre o agente."),
            D("followup", "Seguimento", "O paciente será liberado após o manejo inicial.",
              "Qual safety-netting é melhor?",
              "Retornar precocemente se febre, piora, expansão da vermelhidão, dor desproporcional ou nova coleção.",
              "Retornar apenas se ainda houver secreção após sete dias.",
              "Não retornar se estiver usando antibiótico.",
              "Manipular a lesão em casa até esvaziar totalmente."),
        ],
    },
    2: {
        "title": "Impetigo bacteriano com provável participação de Staphylococcus aureus",
        "focus": "Lesões crostosas, S. aureus/estreptococos, extensão, terapia proporcional e transmissão.",
        "sources": GENERAL_SOURCES,
        "nodes": [
            D("recognition", "Síndrome", "Criança com lesões superficiais crostosas e prurido leve, sem toxemia.",
              "Qual hipótese orienta melhor a consulta?",
              "Impetigo; avaliar número de lesões, bolhas, celulite, febre e contatos.",
              "Dermatite de contato com possível infecção secundária; examinar toda a pele.",
              "Herpes-zóster como hipótese principal.",
              "Tuberculose cutânea."),
            D("etiology", "Agente", "Há crostas melicéricas e ausência de abscesso profundo.",
              "Qual associação etiológica é mais adequada?",
              "Staphylococcus aureus, podendo haver participação de estreptococos beta-hemolíticos.",
              "S. aureus apenas; estreptococos nunca causam impetigo.",
              "Escherichia coli por contaminação fecal.",
              "Mycobacterium tuberculosis."),
            D("testing", "Exames", "Primeiro episódio, poucas lesões e criança bem.",
              "Você solicita cultura?",
              "Não de rotina; reservar para falha, recorrência, surto, extensão relevante ou dúvida.",
              "Solicitar se não houver melhora com o manejo inicial.",
              "Cultivar todas as lesões antes de iniciar higiene local.",
              "Pedir hemocultura em toda criança com impetigo."),
            D("treatment", "Tratamento", "Poucas lesões localizadas, sem febre ou celulite.",
              "Qual estratégia é mais racional?",
              "Higiene e terapia tópica apropriada conforme protocolo; reservar terapia sistêmica para doença extensa/complicada.",
              "Antibiótico oral estreito contra cocos Gram-positivos mesmo em quadro pequeno.",
              "Antisséptico isolado e compartilhamento normal de toalhas.",
              "Corticoide tópico potente sobre as lesões."),
            D("prevention", "Prevenção", "Um irmão começou com lesão semelhante.",
              "Qual orientação tem maior valor?",
              "Higiene das mãos, não compartilhar objetos/toalhas, unhas curtas, cuidado das lesões e avaliação de contatos sintomáticos.",
              "Separar utensílios pessoais e reforçar higiene.",
              "Dar antibiótico profilático para toda a família.",
              "Informar que não há transmissão pessoa a pessoa."),
            D("alarm", "Complicação", "Surge febre e eritema doloroso em expansão ao redor das lesões.",
              "O que fazer?",
              "Reavaliar imediatamente para celulite/infecção profunda e gravidade, ajustando terapia e nível de cuidado.",
              "Trocar apenas a pomada e reavaliar em uma semana.",
              "Manter tudo igual porque crostas podem ficar vermelhas.",
              "Suspender higiene porque irrita a pele."),
        ],
    },
    3: {
        "title": "Pneumonia adquirida na comunidade com suspeita de Streptococcus pneumoniae",
        "focus": "PAC, gravidade, pneumococo, exames seletivos, antibiótico proporcional e reavaliação.",
        "sources": GENERAL_SOURCES,
        "nodes": [
            D("severity", "Gravidade", "Febre, tosse produtiva e dor pleurítica há poucos dias.",
              "O que deve vir antes de escolher antibiótico?",
              "Avaliar FR, saturação, pressão, estado mental, hidratação, comorbidades e capacidade de cuidado domiciliar.",
              "Auscultar e iniciar tratamento se houver estertores.",
              "Pedir tomografia de tórax para todos.",
              "Dar antitussígeno e aguardar uma semana."),
            D("etiology", "Agente", "Início agudo, expectoração, dor pleurítica e achados focais.",
              "Qual agente bacteriano clássico merece lembrança?",
              "Streptococcus pneumoniae.",
              "Mycoplasma pneumoniae, que também causa PAC mas costuma ter apresentação mais atípica/subaguda.",
              "Pseudomonas aeruginosa em qualquer adulto com tosse.",
              "Bacteroides fragilis."),
            D("testing", "Exames", "Paciente estável, sem hipoxemia e com quadro clínico típico.",
              "Qual postura sobre exames é mais adequada?",
              "Usar quadro clínico e gravidade; pedir imagem/laboratório quando dúvida, gravidade, falha ou mudança do nível de cuidado.",
              "Solicitar radiografia se disponível, sem atrasar manejo de caso claro e estável.",
              "Pedir cultura de escarro em toda PAC leve antes de tratar.",
              "Não medir saturação porque ausculta basta."),
            D("treatment", "Tratamento", "PAC leve na APS, sem fator especial de resistência ou alergia.",
              "Qual princípio terapêutico é melhor?",
              "Usar esquema oral de primeira linha e espectro apropriado para PAC/pneumococo conforme protocolo SUS/local, evitando ampliar cobertura sem risco.",
              "Usar beta-lactâmico oral de primeira linha, como amoxicilina quando compatível com protocolo e paciente.",
              "Começar fluoroquinolona respiratória em todo caso para garantir cobertura.",
              "Não usar antibiótico em nenhuma pneumonia comunitária."),
            D("return", "Reavaliação", "O paciente será tratado em casa.",
              "Qual plano de segurança é mais adequado?",
              "Orientar retorno se piora e reavaliar em 48–72 h ou antes diante de dispneia, febre persistente ou queda do estado geral.",
              "Retornar em sete dias somente se ainda estiver tossindo.",
              "Dispensar retorno porque antibiótico adequado garante resposta.",
              "Interromper o esquema no primeiro dia sem febre."),
            D("redflag", "Urgência", "Na reavaliação há queda da saturação, confusão e hipotensão.",
              "Qual conduta?",
              "Reconhecer gravidade e providenciar encaminhamento emergencial, com suporte inicial conforme capacidade da unidade.",
              "Trocar antibiótico oral e observar algumas horas na UBS.",
              "Solicitar cultura ambulatorial e aguardar resultado.",
              "Mandar para casa com hidratação oral."),
        ],
    },
    4: {
        "title": "Cistite aguda não complicada provável por Escherichia coli",
        "focus": "Cistite versus pielonefrite/IST, E. coli, exames seletivos e terapia de primeira linha.",
        "sources": GENERAL_SOURCES,
        "nodes": [
            D("syndrome", "Risco", "Disúria, polaciúria e urgência, sem corrimento.",
              "Qual pergunta muda mais o nível de risco?",
              "Perguntar febre, dor lombar, vômitos, gestação, alteração urológica e recorrência.",
              "Perguntar apenas ingestão de água.",
              "Perguntar somente história de candidíase.",
              "Não perguntar nada porque disúria confirma cistite."),
            D("etiology", "Agente", "Quadro compatível com cistite comunitária não complicada.",
              "Qual agente é a associação clássica?",
              "Escherichia coli uropatogênica.",
              "Klebsiella pneumoniae, possível mas menos clássica neste cenário.",
              "Chlamydia trachomatis como explicação obrigatória para toda disúria.",
              "Mycobacterium tuberculosis em toda primeira cistite."),
            D("tests", "Exames", "Primeiro episódio, pessoa não gestante e sem sinais de pielonefrite.",
              "Qual estratégia é mais apropriada?",
              "Diagnóstico pode ser clínico; usar EAS/cultura conforme dúvida, recorrência, falha, gestação ou complicação.",
              "Solicitar EAS sempre que estiver facilmente disponível.",
              "Solicitar urocultura em toda cistite simples e aguardar antes de tratar.",
              "Solicitar hemocultura em todo caso de disúria."),
            D("treatment", "Tratamento", "Cistite não complicada confirmada.",
              "Qual princípio é melhor?",
              "Escolher antimicrobiano oral de primeira linha conforme protocolo local, resistência, função renal, alergias e gestação.",
              "Considerar nitrofurantoína quando apropriada ao perfil e à padronização local.",
              "Usar ciprofloxacino como primeira escolha universal por ser mais forte.",
              "Tratar apenas com analgésico urinário e nunca usar antibiótico."),
            D("pitfall", "Armadilha", "Surge história de nova parceria e discreto sangramento pós-coito.",
              "O que muda?",
              "Reabrir o diferencial para uretrite/cervicite e IST, com história sexual respeitosa e manejo protocolar.",
              "Manter cistite, mas perguntar corrimento e dor pélvica antes de decidir.",
              "Somar um segundo antibiótico urinário sem nova avaliação.",
              "Ignorar informação sexual porque não tem relação com disúria."),
            D("redflag", "Progressão", "No dia seguinte: febre alta, vômitos e dor lombar.",
              "Qual decisão é correta?",
              "Reclassificar como possível ITU alta/complicada, colher cultura quando possível e avaliar necessidade de encaminhamento.",
              "Trocar antibiótico oral e agendar retorno em cinco dias.",
              "Manter manejo de cistite porque o agente provável pode continuar sendo E. coli.",
              "Suspender avaliação porque sintomas urinários oscilam."),
        ],
    },
    5: {
        "title": "ITU febril/complicada com possível Klebsiella pneumoniae",
        "focus": "Pielonefrite/complicação, cultura, resistência, obstrução e nível de cuidado.",
        "sources": GENERAL_SOURCES,
        "nodes": [
            D("severity", "Risco imediato", "Disúria evoluiu para febre e dor lombar.",
              "Qual avaliação não pode faltar?",
              "Sinais vitais, perfusão, estado mental, vômitos, hidratação, gestação e sinais de sepse.",
              "Punho-percussão lombar e temperatura.",
              "Ultrassom antes de medir sinais vitais.",
              "Tratar como cistite simples porque começou com disúria."),
            D("risk", "Complicadores", "Há diabetes e história de cálculo renal.",
              "Por que isso importa?",
              "Aumenta preocupação com ITU complicada, obstrução, pior evolução e necessidade de cultura/imagem/encaminhamento.",
              "Apenas aumenta recorrência, sem mudar manejo agudo.",
              "Significa que o agente obrigatoriamente será Klebsiella.",
              "Diabetes protege contra bacteremia."),
            D("micro", "Microbiologia", "Suspeita de pielonefrite complicada.",
              "Qual estratégia microbiológica é melhor?",
              "Coletar urocultura antes do antibiótico quando viável, sem atrasar caso grave, e ajustar pelo antibiograma.",
              "Coletar EAS e cultura, iniciando tratamento sem esperar resultado se houver indicação.",
              "Aguardar antibiograma 48–72 h antes de tratar qualquer paciente.",
              "Não colher cultura porque Klebsiella é sempre sensível."),
            D("etiology", "Agente", "A cultura identifica Klebsiella pneumoniae.",
              "Qual interpretação é adequada?",
              "É enterobactéria capaz de causar ITU e adquirir resistência relevante; tratar conforme sensibilidade e contexto.",
              "É agente plausível de ITU complicada e o antibiograma orienta refinamento.",
              "Klebsiella significa automaticamente infecção hospitalar.",
              "Klebsiella é fungo oportunista."),
            D("treatment", "Tratamento", "Paciente taquicárdico, vomitando e sem tolerância oral.",
              "Qual decisão é melhor?",
              "Encaminhar para maior complexidade, iniciar suporte e antimicrobiano empírico conforme protocolo/gravidade e depois ajustar à cultura.",
              "Dar primeira dose parenteral se prevista no protocolo e organizar encaminhamento imediato.",
              "Prescrever nitrofurantoína oral porque serve para qualquer ITU.",
              "Somente hidratação oral em casa."),
            D("source", "Controle de foco", "Dor intensa e suspeita de obstrução por cálculo.",
              "Qual conceito é essencial?",
              "Infecção com obstrução pode exigir descompressão urgente; antibiótico isolado pode não controlar o foco.",
              "Solicitar imagem e discutir urologia/urgência conforme achados.",
              "Aumentar dose do antibiótico e aguardar eliminação espontânea do cálculo.",
              "Obstrução não interfere no tratamento infeccioso."),
        ],
    },
    6: {
        "title": "Ferida crônica com risco de Pseudomonas aeruginosa",
        "focus": "Colonização versus infecção, amostra profunda, fatores de risco e stewardship antipseudomonas.",
        "sources": GENERAL_SOURCES,
        "nodes": [
            D("assessment", "Ferida crônica", "Ferida antiga passou a ter mais secreção e odor.",
              "Qual primeira avaliação é mais importante?",
              "Comparar com basal e procurar dor crescente, eritema, calor, necrose, sinais sistêmicos, perfusão e profundidade.",
              "Registrar cor/odor e fotografar.",
              "Considerar todo odor como infecção por Pseudomonas.",
              "Cobrir sem examinar para evitar contaminação."),
            D("colonization", "Colonização x infecção", "Paciente estável, sem celulite ao redor.",
              "Qual princípio é correto?",
              "Bactéria na superfície não equivale a infecção invasiva; tratar o quadro clínico, não apenas um swab positivo.",
              "Priorizar cuidado da ferida e reavaliar, reservando antibiótico sistêmico para indicação clínica.",
              "Qualquer crescimento bacteriano exige antibiótico sistêmico.",
              "Ferida crônica nunca infecta."),
            D("sample", "Amostra", "Há sinais clínicos de infecção e microbiologia pode mudar conduta.",
              "Qual amostra tem maior valor?",
              "Amostra profunda/tecido após técnica adequada, conforme protocolo, em vez de swab superficial indiscriminado.",
              "Swab após limpeza se for a única técnica disponível e houver indicação.",
              "Swab da secreção externa antes de limpar.",
              "Cultura do curativo usado."),
            D("etiology", "Agente", "Múltiplos antibióticos prévios, internações e ferida úmida crônica.",
              "Qual conclusão é adequada?",
              "Pseudomonas aeruginosa fica mais plausível, mas depende de síndrome clínica e microbiologia; cor/odor não confirmam.",
              "Pseudomonas deve entrar no diferencial.",
              "Se secreção for esverdeada, Pseudomonas está confirmada.",
              "Pseudomonas só causa pneumonia hospitalar."),
            D("treatment", "Stewardship", "Sem sinais sistêmicos/invasivos; swab superficial cresceu Pseudomonas.",
              "Qual conduta é melhor?",
              "Não iniciar antipseudomonas sistêmico só pelo swab; otimizar ferida, perfusão e fatores predisponentes e reavaliar.",
              "Reavaliar e obter amostra melhor se houver suspeita real de infecção.",
              "Iniciar ciprofloxacino automaticamente por causa do laudo.",
              "Usar dois antipseudomonas preventivamente."),
            D("redflag", "Emergência", "Dor desproporcional, necrose e rápida progressão.",
              "Qual decisão?",
              "Suspeitar infecção profunda/necrosante ou isquemia e encaminhar emergencialmente para avaliação cirúrgica/hospitalar.",
              "Iniciar antibiótico amplo e organizar transferência imediata.",
              "Aguardar cultura profunda antes de encaminhar.",
              "Fazer apenas curativo mais oclusivo."),
        ],
    },
    7: {
        "title": "Infecção intra-abdominal com provável participação de Bacteroides fragilis",
        "focus": "Ruptura de barreira, anaeróbios, controle de foco e limite da APS.",
        "sources": GENERAL_SOURCES,
        "nodes": [
            D("redflag", "Abdome agudo", "Dor abdominal progressiva e febre após quadro compatível com ruptura de víscera.",
              "Qual é a prioridade na UBS?",
              "Avaliar instabilidade, peritonismo e sepse e organizar encaminhamento hospitalar urgente.",
              "Fazer exame abdominal e sinais vitais antes de decidir encaminhamento.",
              "Dar antiespasmódico e rever em 48 h.",
              "Orientar dieta leve e repouso."),
            D("etiology", "Agente", "Suspeita de perfuração/abscesso de origem intestinal.",
              "Por que Bacteroides fragilis é relevante?",
              "É anaeróbio da microbiota colônica que pode causar doença quando a barreira intestinal é rompida.",
              "É flora intestinal e pode participar de infecção polimicrobiana.",
              "É adquirido principalmente por gotículas.",
              "É vírus entérico."),
            D("sample", "Microbiologia", "No hospital, uma coleção é drenada.",
              "Qual amostra é melhor para anaeróbios?",
              "Aspirado/tecido profundo coletado e transportado adequadamente para preservar anaeróbios.",
              "Material profundo seguindo orientação do laboratório.",
              "Swab superficial da pele sobre a dor.",
              "Saliva do paciente."),
            D("source", "Controle de foco", "Imagem mostra coleção intra-abdominal.",
              "Qual conceito é central?",
              "Antibiótico deve ser combinado ao controle de foco quando indicado — drenagem/procedimento cirúrgico.",
              "Iniciar antibiótico e solicitar avaliação cirúrgica.",
              "Aumentar progressivamente o espectro até a coleção desaparecer.",
              "Não usar antibiótico em infecção intra-abdominal."),
            D("coverage", "Cobertura", "Infecção complicada de origem colônica.",
              "Qual princípio orienta o esquema?",
              "Cobrir flora entérica relevante, incluindo anaeróbios, conforme protocolo hospitalar, gravidade e epidemiologia, descalonando quando possível.",
              "Escolher esquema com atividade contra Gram-negativos e anaeróbios.",
              "Usar apenas penicilina benzatina porque é bactéria.",
              "Usar antiviral de amplo espectro."),
            D("aps", "Limites da APS", "A família pergunta se pode tratar apenas com comprimidos em casa.",
              "Qual resposta é melhor?",
              "Explicar que peritonite/coleção/sepse exige avaliação hospitalar; a APS reconhece risco, inicia suporte possível e coordena encaminhamento.",
              "Dizer que talvez seja possível após estabilização e avaliação especializada.",
              "Aceitar tratamento domiciliar sem discutir o risco.",
              "Dizer que todo problema abdominal é cirúrgico."),
        ],
    },
    8: {
        "title": "Tuberculose pulmonar por Mycobacterium tuberculosis",
        "focus": "Sintomático respiratório, diagnóstico no SUS, esquema básico, contatos, HIV e adesão.",
        "sources": GENERAL_SOURCES + [
            {
                "title": "Ministério da Saúde — Tuberculose",
                "url": "https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/t/tuberculose",
            },
            {
                "title": "Manual de Recomendações para o Controle da Tuberculose no Brasil",
                "url": "https://www.gov.br/aids/pt-br/central-de-conteudo/publicacoes/2020/manual-de-recomendacoes-para-o-controle-da-tuberculose-no-brasil",
            },
        ],
        "nodes": [
            D("recognition", "Reconhecimento", "Tosse persistente há semanas, emagrecimento e sudorese noturna.",
              "Qual hipótese precisa ser investigada ativamente?",
              "Tuberculose pulmonar, sem deixar de avaliar diagnósticos diferenciais e gravidade.",
              "Pneumonia comum, mantendo TB apenas como diferencial tardio.",
              "Alergia respiratória apesar do emagrecimento.",
              "Cistite recorrente."),
            D("infection", "Transmissão", "Paciente permanece tossindo enquanto aguarda investigação.",
              "Qual medida é mais apropriada?",
              "Seguir medidas de controle respiratório do serviço, favorecer ventilação e orientar etiqueta respiratória/máscara conforme indicação.",
              "Manter em área ventilada e reduzir espera desnecessária.",
              "Usar apenas luvas porque TB transmite por contato.",
              "Não adotar precaução até cultura positiva."),
            D("diagnosis", "Diagnóstico", "A suspeita clínica é relevante.",
              "Qual investigação etiológica está mais alinhada ao SUS?",
              "Teste rápido molecular quando disponível, com baciloscopia/cultura conforme algoritmo e situação clínica.",
              "Baciloscopia e radiografia, acrescentando método molecular conforme disponibilidade.",
              "Sorologia IgG para confirmar TB ativa.",
              "Hemograma normal exclui tuberculose."),
            D("biology", "Microbiologia", "Teste confirma complexo Mycobacterium tuberculosis.",
              "Qual característica tem consequência clínica?",
              "Parede rica em lipídios/ácidos micólicos e crescimento lento ajudam a explicar diagnóstico específico e tratamento prolongado.",
              "É bacilo álcool-ácido resistente de crescimento lento.",
              "Não possui parede celular, como Mycoplasma.",
              "É coco Gram-positivo encapsulado."),
            D("treatment", "Tratamento", "TB pulmonar sensível confirmada, sem situação especial.",
              "Qual princípio é correto?",
              "Iniciar esquema básico padronizado pelo SUS com rifampicina, isoniazida, pirazinamida e etambutol, pelo tempo recomendado e com acompanhamento.",
              "Usar esquema básico do SUS e monitorar adesão/eventos adversos, sem nomear os fármacos.",
              "Usar amoxicilina por dez dias e repetir radiografia.",
              "Tratar com um único fármaco para reduzir toxicidade."),
            D("publichealth", "APS e vigilância", "Além de prescrever, há responsabilidades de saúde pública.",
              "O que faz parte do cuidado?",
              "Notificação, testagem para HIV conforme protocolo, avaliação de contatos, apoio à adesão/TDO quando indicado e seguimento longitudinal.",
              "Avaliar contatos domiciliares e acompanhar adesão.",
              "Orientar o paciente a tratar sozinho e não informar contatos.",
              "Dar alta após a primeira melhora da tosse."),
        ],
    },
    9: {
        "title": "Infecção respiratória por Mycoplasma pneumoniae",
        "focus": "Padrão atípico, ausência de parede celular, gravidade e antimicrobiano com atividade apropriada.",
        "sources": GENERAL_SOURCES,
        "nodes": [
            D("pattern", "Padrão clínico", "Jovem com tosse seca persistente, febre baixa/moderada e estado geral preservado.",
              "Qual raciocínio é mais adequado?",
              "Considerar pneumonia por agentes atípicos, incluindo Mycoplasma, sem deixar de estratificar gravidade.",
              "Considerar virose e manter pneumonia atípica no diferencial.",
              "Diagnosticar pneumococo apenas porque há febre.",
              "Diagnosticar Bacteroides fragilis."),
            D("severity", "Gravidade", "Antes de escolher tratamento.",
              "Qual conjunto deve ser checado?",
              "Saturação, frequência respiratória, pressão, estado mental, hidratação e comorbidades.",
              "Ausculta e temperatura.",
              "Apenas radiografia.",
              "Nenhum sinal vital porque o paciente é jovem."),
            D("biology", "Biologia", "O agente provável é Mycoplasma pneumoniae.",
              "Qual característica tem maior consequência terapêutica?",
              "Ausência de parede celular, tornando beta-lactâmicos ineficazes como terapia dirigida ao agente.",
              "É bactéria pequena sem parede celular, sem explicitar a implicação terapêutica.",
              "Forma endósporos resistentes à penicilina.",
              "É vírus de RNA."),
            D("tests", "Exames", "Caso leve, típico, sem surto ou complicação.",
              "Qual postura é razoável?",
              "Diagnóstico pode ser clínico/sindrômico; reservar testes/imagem para gravidade, surto, dúvida ou mudança de conduta.",
              "Solicitar radiografia se houver dúvida diagnóstica.",
              "Solicitar cultura bacteriana comum de rotina para Mycoplasma.",
              "Confirmar por Gram do escarro."),
            D("treatment", "Tratamento", "Há indicação de antimicrobiano e o quadro é compatível com Mycoplasma.",
              "Qual princípio é melhor?",
              "Usar agente ativo contra patógenos atípicos conforme protocolo e perfil; não usar beta-lactâmico isolado como terapia dirigida a Mycoplasma.",
              "Considerar macrolídeo ou doxiciclina quando apropriado a protocolo, idade e contraindicações.",
              "Usar amoxicilina isoladamente porque é primeira linha para qualquer pneumonia.",
              "Usar antifúngico."),
            D("reassess", "Reavaliação", "Após 48–72 h há piora da dispneia e queda da saturação.",
              "O que fazer?",
              "Reavaliar diagnóstico e gravidade e encaminhar conforme necessidade.",
              "Rever adesão/terapia e checar sinais de gravidade.",
              "Apenas dobrar a dose do antibiótico em casa.",
              "Ignorar porque tosse por Mycoplasma pode durar semanas."),
        ],
    },
    10: {
        "title": "Uretrite/cervicite por Chlamydia trachomatis",
        "focus": "História sexual respeitosa, clamídia, NAAT, tratamento conforme PCDT-IST e parcerias.",
        "sources": GENERAL_SOURCES + [
            {
                "title": "Ministério da Saúde — PCDT para Atenção Integral às Pessoas com IST",
                "url": "https://www.gov.br/saude/pt-br/assuntos/pcdt/a/atencao-integral-as-pessoas-com-infeccoes-sexualmente-transmissiveis/view",
            },
            {
                "title": "Ministério da Saúde — Clamídia",
                "url": "https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/c/clamidia/clamidia",
            },
        ],
        "nodes": [
            D("history", "Abordagem", "Disúria após nova parceria sexual e sintomas geniturinários leves.",
              "Qual abordagem é melhor?",
              "História sexual respeitosa/confidencial: práticas, preservativo, corrimento, dor pélvica/testicular, gestação e outras exposições.",
              "Perguntar apenas se houve relação sem preservativo.",
              "Presumir cistite e evitar perguntas íntimas.",
              "Repreender o paciente pelo comportamento sexual."),
            D("etiology", "Agente", "Há uretrite/cervicite sem sinais de ITU alta.",
              "Qual agente deve ser fortemente considerado?",
              "Chlamydia trachomatis.",
              "Neisseria gonorrhoeae, diferencial importante e possível coinfecção.",
              "Escherichia coli exclusivamente porque toda disúria é ITU.",
              "Bacteroides fragilis."),
            D("test", "Diagnóstico", "É possível investigar etiologia.",
              "Qual teste é preferível quando disponível?",
              "Teste molecular de amplificação de ácidos nucleicos (NAAT) em amostra validada para o sítio, conforme protocolo.",
              "NAAT em urina de primeiro jato ou swab apropriado, sem considerar outros sítios de exposição.",
              "Urocultura comum para procurar clamídia.",
              "Hemograma normal exclui IST."),
            D("treatment", "Tratamento", "Clamídia confirmada, sem complicação.",
              "Qual conduta é mais apropriada?",
              "Tratar conforme PCDT-IST vigente, escolhendo esquema recomendado — como doxiciclina ou azitromicina conforme situação/gestação — e orientar prevenção.",
              "Usar um dos esquemas recomendados e programar seguimento, sem abordar situações especiais/parcerias.",
              "Usar penicilina benzatina porque trata todas as IST bacterianas.",
              "Não tratar porque clamídia pode ser assintomática."),
            D("partners", "Parcerias", "O paciente pergunta se a parceria precisa ser avisada.",
              "Qual orientação é melhor?",
              "Parcerias devem ser avaliadas/manejadas conforme PCDT, com oferta de testagem para outras IST e prevenção.",
              "Orientar comunicação à parceria e preservativo até completar o manejo.",
              "Avisar somente se a parceria tiver sintomas.",
              "Nunca abordar parcerias por confidencialidade."),
            D("complication", "Complicações", "Surge dor pélvica intensa e febre ou, em outro paciente, dor testicular aguda.",
              "O que muda?",
              "Avaliar imediatamente DIP/epididimite e diagnósticos urgentes, ajustando tratamento e encaminhamento conforme protocolo.",
              "Ampliar exame físico e verificar gravidade antes de decidir.",
              "Manter o mesmo plano porque o agente continua clamídia.",
              "Orientar apenas analgésico e retorno em uma semana."),
        ],
    },
}


def _profile_index(case):
    if case.category != ClinicalCase.Category.BACTERIA:
        raise ValueError("Árvore decisória disponível apenas para casos bacterianos nesta etapa.")
    order = int(case.order)
    if not 1 <= order <= 20:
        raise ValueError("Caso bacteriano fora da faixa B01–B20.")
    return ((order - 1) // 2) + 1


def _ordered_options(case_code, node):
    options = deepcopy(node["options"])
    return sorted(
        options,
        key=lambda opt: hashlib.sha256(
            f"{case_code}:{node['id']}:{opt['id']}".encode("utf-8")
        ).digest(),
    )


def get_tree(case):
    base = SCENARIOS[_profile_index(case)]
    variant = 1 if int(case.order) % 2 else 2
    nodes = []
    for node in base["nodes"]:
        rendered = deepcopy(node)
        rendered["options"] = _ordered_options(case.code, rendered)
        nodes.append(rendered)
    return {
        "case_code": case.code,
        "title": base["title"],
        "focus": base["focus"],
        "variant": variant,
        "variant_note": (
            "Primeiro episódio, sem tratamento específico prévio."
            if variant == 1
            else "Quadro persistente após medidas caseiras/sintomáticas, sem tratamento etiológico prévio."
        ),
        "sources": deepcopy(base["sources"]),
        "nodes": nodes,
        "max_points": sum(max(option["points"] for option in node["options"]) for node in nodes),
    }


def find_option(tree, node_id, option_id):
    node = next((item for item in tree["nodes"] if item["id"] == node_id), None)
    if not node:
        return None, None
    option = next((item for item in node["options"] if item["id"] == option_id), None)
    return node, option
